Add Feed class
adobe/aepsdk-messaging-android pull request #162
Opened 2023-03-28 21:39 UTC by rymorale

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-30 17:22 UTC, swarna04 requested changes
Can we please add some tests for this class as well. Ty.

2023-04-03 18:54 UTC, swarna04 commented on code/messaging/src/main/java/com/adobe/marketing/mobile/Feed.java
> +        this.name = name;
As I mentioned earlier, this value can be read from the feed item meta, see https://github.com/adobe/aepsdk-messaging-ios/pull/172/files#diff-c50733277af431f090093fc86cce41d5c704438bcd865c67bc59f0480b33a20aR31. I'm currently reading the first feed item's meta info to determine the feed name (might change in future). I'm fine if you want to accept the value in the constructor for now and revise it later.

2023-04-03 18:54 UTC, swarna04 approved these changes

2023-04-03 18:57 UTC, rymorale commented on code/messaging/src/main/java/com/adobe/marketing/mobile/Feed.java
> +        this.name = name;
my bad, i'll fix this and update the constructor

2023-04-03 19:24 UTC, merged