[MOB-19239] Update feed retrieval from remote
adobe/aepsdk-messaging-android pull request #187
Opened 2023-07-31 16:20 UTC by rymorale

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-31 23:03 UTC, swarna04 requested changes

2023-08-01 00:53 UTC, rymorale commented on code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
> +    public static Surface fromString(final String path) {
i need to keep it public as its called from MessagingUtils: https://github.com/rymorale/aepsdk-messaging-android/blob/update-feed-retrieval-from-remote/code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java#L161-L172

2023-08-01 01:06 UTC, rymorale commented on code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
> +        this(false, null);
yeah I think that is a better way to do it. will update it.

2023-08-02 19:32 UTC, swarna04 approved these changes

2023-08-02 19:32 UTC, swarna04 commented on code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
> +    public static Surface fromUriString(final String path) {
As per previous feedback, also requested renaming path->uri

2023-08-02 19:32 UTC, swarna04 commented on code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
> +            return null;
nit: Let us provide a debug log here before returning null.

2023-08-02 20:10 UTC, merged