Merge feature/create push notification to staging for Messaging 1.1.0 release
adobe/aepsdk-messaging-android pull request #86
Opened 2022-06-08 16:46 UTC by rymorale

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-10 21:24 UTC, swarna04 requested changes

2022-06-10 21:24 UTC, swarna04 commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushNotificationFactory.java
> +        notificationBuilder.setContentTitle(payload.getTitle());
Shouldn't we verify that payload is not null?

2022-06-10 21:24 UTC, swarna04 commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushNotificationFactory.java
> +        notificationBuilder.setSmallIcon(smallIcon);
Verify non-null Notification builder is supplied.

2022-06-10 21:24 UTC, swarna04 commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingUtils.java
> +        final int resID = context.getResources().getIdentifier(fileName, "raw", context.getPackageName());
use camelCase for variable here.

2022-06-13 22:49 UTC, rymorale commented on code/app/build.gradle
> +        edge       : "com.adobe.marketing.mobile:edge:1.1.0",
This is the minimum required so I can use regex to get the latest 1.+. version.

2022-06-13 22:50 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingInternal.java
> +        final String adobe = eventData.optString(MessagingConstants.EventDataKeys.Messaging.TRACK_INFO_KEY_ADOBE_XDM, null);
yes this is clearer

2022-06-13 22:51 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingDefaultImageDownloader.java
> +     * TODO: Store the image asset in the disk cache added in the feature/iam branch
this is addressed in https://github.com/adobe/aepsdk-messaging-android/pull/88

2022-06-13 22:53 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingImageDownloaderTask.java
> +            connection = (HttpURLConnection) imageUrl.openConnection();
i've migrated to using the RemoteDownloader and our extension cache in this pr: https://github.com/adobe/aepsdk-messaging-android/pull/88

2022-06-14 16:43 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingDefaultImageDownloader.java
> +    private void addBitmapToMemCache(String key, Bitmap bitmap) {
these functions are removed in https://github.com/adobe/aepsdk-messaging-android/pull/88

2022-06-14 16:43 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingDefaultImageDownloader.java
> +    private Bitmap getBitmapFromMemCache(String key) {
these functions are removed in https://github.com/adobe/aepsdk-messaging-android/pull/88

2022-06-14 16:44 UTC, rymorale commented on code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingDefaultImageDownloader.java
> +        final int cacheSize = maxMemory / 8;
this is updated as well in https://github.com/adobe/aepsdk-messaging-android/pull/88

2023-02-13 19:20 UTC, closed without merging